# Discussion

---
execute:
  echo: false
  freeze: auto
format:
  html:
    code-fold: true
    code-tools: true
    code-summary: "Show the code"
---

Discussion among the research team is currently in progress on the following topics:

## Water Temperature Metrics and Anadromous Habitat

Hydrology model outputs from this project will provide spatially explicit projections of possible future discharge and temperature conditions for Beaver Creek under scenarios of climate change and groundwater withdrawal. We anticipate that discharge and temperature will vary by scenario in ways meaningful to aquatic habitat throughout Beaver Creek. We intend to evaluate these predictions against criteria found in the literature to help understand potential effects on fish, particularly anadromous (e.g. salmonid) species.

The following is a discussion of potentially relevant water temperature metrics. Depending on the time scale of model outputs, some metrics may be more applicable than others.

### Water Temperature Metrics

A suite of over fifty distinct temperature metrics may be calculated using an existing R script published in Appendix B of 2013 USGS report focused on cold-water streams in the Nevada desert [@falke2013][^discussion-1].

[^discussion-1]: <https://paperpile.com/app/p/c29b459f-89c7-03ee-ad79-c4c9c9cfd817>

The list of 52 metrics each fall in to one of the following five categories:

-   Magnitude

-   Variation

-   Frequency

-   Duration

-   Timing

From this list, researchers in [@mauger2017] chose three specific metrics to evaluate when considering regional-scale variations of lotic freshwater thermal regimes in the Cook Inlet region:

> "We selected three metrics to describe aspects of the summer temperature regimes in the 48 streams: mean July temperature, maximum weekly average temperature (MWAT), and maximum weekly maximum temperature (MWMT). We chose mean July stream temperature because this is typically the hottest month in southcentral Alaska. We calculated mean July temperature only for site-years when at least 90% of the days were captured (\>27 days). We used MWAT and MWMT because they represent an intermediate time period over which transient high temperatures may affect fitness in aquatic organisms.

Researchers focusing on stream temperatures in the nearby Mat-Su valley region used a cluster analysis to characterize thermal regimes using a different subset of descriptors [@shaftel2020]:

> \[We used\] ... metrics that represent the magnitude, variability, frequency, duration, and timing of temperature events related to salmon life histories. We used cluster analysis to characterize thermal regimes present in the Matanuska-Susitna (Mat-Su) Basin based on 10 nonredundant temperature metrics and identified the most important drivers of our thermal regimes using random forests.

Both of these manuscripts focused on southcentral Alaska temperature regimes are relevant to our work focused on Beaver Creek, but are focused on distinguishing and decribing thermal regimes rather than specifically on biological effects on anadromous species.

Meyer et al. used a bioenergetics modeling approach to evaluate potential effects of water temperature and food consumption on summer growth rates of juvenile Chinook and coho salmon in the Kenai River watershed [@meyer2023].

#### State and Federal Water Temperature Mangement Criteria

-   ADEC Values
-   EPA values

A basic potential approach -- for each stream segment under each scenario (climate/flow/time period), evaluate the total proportion of time spent above state & federal criteria value. Likely to see meaningful spatial variation.

[Work in progress here.]
